ALTER TABLE questions ALTER COLUMN option_a TYPE TEXT;
ALTER TABLE questions ALTER COLUMN option_b TYPE TEXT;
ALTER TABLE questions ALTER COLUMN option_c TYPE TEXT;
ALTER TABLE questions ALTER COLUMN option_d TYPE TEXT;
ALTER TABLE questions ALTER COLUMN correct_answer TYPE TEXT;
ALTER TABLE questions ALTER COLUMN topic TYPE VARCHAR(1000);
