spring.application.name=AssessMate

spring.datasource.url=jdbc:postgresql://localhost:1234/assessmate
spring.datasource.username=postgres
spring.datasource.password=9094

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080

#jwt
jwt.secret=assessmate_secret_key_very_long_string_2026_keep_private
jwt.expiration=86400000